### ISSUE TITLE
Bug in vless sub

### ISSUE THREAD

**Issue by Knight5789** [barry-far/V2ray-Configs#10]
In checking servers app stopped and exit  I'm checking all my sub but you're  sub only has this problem
  
This issue has been tested in nekobox and nekoray

**Comment by barry-far** [comment]
Hi @Knight5789 ,
Thanks for sharing your problem
As many users told me in my twitter account , I made multiple subs that clients can read & decode them all. if you have any other problem , feel free to ask :)

**Use These sublinks** :

Subscription 1: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt`

Subscription 2: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt`

Subscription 3: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt`

Subscription 4: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt`

Subscription 5: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt`

Subscription 6: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt`

Subscription 7: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt`

Subscription 8: `https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub8.txt`

**Comment by Knight5789** [comment]
Hi, thanks for your feedback

In my opinion, these problems are completely intentional. There are a number of faulty proxies spread on Telegram and the Internet and they cause such errors and problems. In my opinion, this issue should be resolved by testing them or by solving the problem in the clients.

**Comment by barry-far** [comment]
> There are a number of faulty proxies spread on Telegram and the Internet and they cause such errors and problems

Hi again @Knight5789 ,
As you can see in `app.py` , the code only transforms the v2ray configs without any other words.

I see you are using the protocol-splitted sub & with that sub your client would be crashed...

I said earlier , if you use the splitted sub , you wont have any problems either....  💯

_Making the splitted protocol sub, more parts will be same main subs.😒_
