### ISSUE TITLE
The latest version of V2rayN V6.33 in Windows cannot import configurations.

### ISSUE THREAD

**Issue by ohyoxo** [barry-far/V2ray-Configs#19]
In the latest version V6.33 of V2rayN in Windows 10, the following step is no longer available. How should I import it?

To import a configuration file in V2rayN, simply right-click on the V2rayN icon in the system tray, select "Import from clipboard", and paste the configuration link. For the official client, click on the "V" icon in the system tray and select "Import Config".

**Comment by barry-far** [comment]
Hi @ohyoxo,

could you give me any screen shot of your problem ??

**Comment by ohyoxo** [comment]
> Hi @ohyoxo,
> 
> could you give me any screen shot of your problem ??

![image](https://github.com/barry-far/V2ray-Configs/assets/126952400/ef86035d-29e5-4528-b4ee-0a9104dd88e6)

V2rayN does not have this option："Import Config"

**Comment by barry-far** [comment]
> > Hi @ohyoxo,
> > could you give me any screen shot of your problem ??
> 
> ![image](https://private-user-images.githubusercontent.com/126952400/305649194-ef86035d-29e5-4528-b4ee-0a9104dd88e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDA3NjAsIm5iZiI6MTcwODQ0MDQ2MCwicGF0aCI6Ii8xMjY5NTI0MDAvMzA1NjQ5MTk0LWVmODYwMzVkLTI5ZTUtNDUyOC1iNGVlLTBhOTEwNGRkODhlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNDQ3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmZlMzk5NTNiOTBmZWEwOGVmNzY4Yjk4MWFiZjkxZDlkNjU3YTRkNThlMThkNzA4ZDdmZDAzYTU3ODEzYmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6s_Sd6tgbSFa3xLGlKKhH2vvmED43ZYF70bvMSXBXwA)
> 
> V2rayN does not have this option："Import Config"

Hi again,
Now i see you didnt opened the application & you are using systemtray window to reach import.
I have so many suggestions for you :

1. you can use its recommended alternative `Hiddify-Next` & you can find versions in [here](https://github.com/hiddify/hiddify-next)
2. you can use another alternative which is `Nekoray` and you can find it [here](https://github.com/MatsuriDayo/nekoray/releases)
