### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by satanec** [barry-far/V2ray-Configs#21]
.سلام، جدیدا قابلیت هایی اضافه شده که از سرویس وارپ کلودفلیر برای امنیت سرور ها استفاده میکنند مانند نسخه بتا hiddify من اطلاعات کافی ندارم. لطف میکنید مطلبی در موردش بنویسید و اگر امکانش هست دسته بندی ای برای اون سرور ها در نظر بگیرید یا …. ممنون میشم

**Comment by barry-far** [comment]
سلام @satanec ، 
متاسفانه من هم اطلاعاتی دربارش ندارم ولی حتماً تحقیق میکنم و داخل x م میزارم : https://twitter.com/fard1627
