### ISSUE TITLE
测速时显示运行core失败，请查看日志

### ISSUE THREAD

**Issue by dreamer-leo** [barry-far/V2ray-Configs#23]
订阅链接运行在v2rayN-v6.29上，一键测速多个节点延迟和速度时，显示运行core失败，请查看日志。

**Comment by barry-far** [comment]
Hi @dreamer-leo , 
Please create your issue in official v2rayN , the problem is not from my side...

**Comment by dreamer-leo** [comment]
ok , thank you !
