### ISSUE TITLE
ایگنور کردن لینک های اشتراک خراب

### ISSUE THREAD

**Issue by coldwater-10** [barry-far/V2ray-Configs#28]
سلام خسته نباشی نمیشه یه قابلیت اضافه کنی لینکای اشتراکی که خراب شدن رو ایگنور کنه بره لینک بعدی کل فرایندش متوقف نشه

**Comment by barry-far** [comment]
سلام @coldwater-10 ،
ممنون از ریپورتت. منظورت از لینک خراب رو متوجه نشدم! یه سری ساب لینک ها به دلیل کم و زیاد شدن کانفیگ ها ممکن هستند که برای مدتی نباشن.
برای همین پیشنهادم اینه که از ساب لینک `all_configs_sub` استفاده کنی به ویژه روی کلاینت `hiddify` که هنگ نکنه.

> سلام خسته نباشی نمیشه یه قابلیت اضافه کنی لینکای اشتراکی که خراب شدن رو ایگنور کنه بره لینک بعدی کل فرایندش متوقف نشه

**Comment by coldwater-10** [comment]
اره منظورمو بد رسوندم من این رپو رو فورک کردم که منابعی که ازش کانفیگ جمع اوری میشه رو بیشتر کنم بعد هر باری که یکی از این منابع به مشکل بخوره کل اکشن متوقف میشه و بروز رسانی نمیکنه میخواستم اگه میشه یه کاری کنی اگه هر کدوم از منابع مشکل داشت متوقف نشه بره منبع بعدی چون تعداد منابعی که گذاشتم زیاده سخته هر بار دستی یکی یکی چک کنم ببینم کدوم به مشکل خورده حذف کنم

**Comment by barry-far** [comment]
> اره منظورمو بد رسوندم من این رپو رو فورک کردم که منابعی که ازش کانفیگ جمع اوری میشه رو بیشتر کنم بعد هر باری که یکی از این منابع به مشکل بخوره کل اکشن متوقف میشه و بروز رسانی نمیکنه میخواستم اگه میشه یه کاری کنی اگه هر کدوم از منابع مشکل داشت متوقف نشه بره منبع بعدی چون تعداد منابعی که گذاشتم زیاده سخته هر بار دستی یکی یکی چک کنم ببینم کدوم به مشکل خورده حذف کنم

حالا متوجه شدم!
ممنون از ریپورتت فکر خیلی خوبیه چون چند روزیه که سورس ها ارور میخورن و job failed میشه...
حتما زودتر آپدیتش میکنم ❤️🫂

**Comment by coldwater-10** [comment]
قربونت موفق باشی ❤️🫂

**Comment by barry-far** [comment]
> قربونت موفق باشی ❤️🫂

خب خب اضافه کردم و مشکل برطرف شده!
fork ت رو بروز کن و لذت ببر ✔️

**Comment by coldwater-10** [comment]
دمت گرم

**Comment by coldwater-10** [comment]
[Sub1.txt](https://github.com/barry-far/V2ray-Configs/blob/main/Sub1.txt)
از دیروز اپدیت نشده که!

**Comment by barry-far** [comment]
> [Sub1.txt](https://github.com/barry-far/V2ray-Configs/blob/main/Sub1.txt) از دیروز اپدیت نشده که!

بله رپو به مشکل خورده بود ولی اروری برنمیگردوند....
الان درسته pull کن.
