### ISSUE TITLE
Hamed550

### ISSUE THREAD

**Issue by Hamedz550** [barry-far/V2ray-Configs#32]
https://github.com/barry-far/V2ray-Configs/blob/3f4f77d617c2b39f0e433adb142e5d6e8a94030a/All_Configs_Sub.txt#L7

**Comment by barry-far** [comment]
سلام @Hamedz550 
این لینک همیشه بروزه و لینک اشتباهی رو کپی کردی 😀 

https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt
