### ISSUE TITLE
Canfing

### ISSUE THREAD

**Issue by 09169471371** [barry-far/V2ray-Configs#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by barry-far** [comment]
Hi @09169471371 ,
You can use this sublink:

[use this](https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_base64_Sub.txt)
