### ISSUE TITLE
A specific request for link. 

### ISSUE THREAD

**Issue by avik-py** [barry-far/V2ray-Configs#47]
I had a VMESS link where it would connect to 185.146.173.59:443(a linode server based in France) but tunneled through a linode server based in mumbai (172.104.207.119). It would allow me to access akamai cache directly, i was able to download steam games with that cached server at maximum speed. I used it for a couple of hours but the destination changed to a linode server based in china and now i cannot access the cache server in mumbai. Is there any way i can find out how to use that again? 
Anyways, thanks for these configs.

**Comment by barry-far** [comment]
Hi @avik-py ,

Thanks for reaching and glad configs helped you. I think you can buy these 2 servers in those locations yourself which you could tunneled them to use for downloading & other stuff. Cause those configs are random and changes each 10 minutes & designed for people who their goverment blocked them to access free internet.

Woman Life Freedom ❤️
