### ISSUE TITLE
alijan101015@gmail.com

### ISSUE THREAD

**Issue by lijan101015** [barry-far/V2ray-Configs#59]
![Uploading 1722382715460.jpg…]()
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lijan101015** [comment]
t

**Comment by lijan101015** [comment]
ali

**Comment by lijan101015** [comment]
hh

**Comment by barry-far** [comment]
@lijan101015 :(

your picture doesnt uploaded!
