### ISSUE TITLE
GitHub文件显示更新了,但是看节点没更新,还有其他问题

### ISSUE THREAD

**Issue by YJL12345** [barry-far/V2ray-Configs#71]
All_Configs_Sub.txt  --  V2rayN
V2ray里面更新节点,但是节点都没有变化,好久了,点击一键测速,core就崩溃,无法运行,以前不会这样的, 我检查过是某些节点不兼容导致的,
我看GitHub文件一直都有更新,不知道什么情况
![image](https://github.com/user-attachments/assets/5eff14bd-7e1b-475d-9e62-9475913cc356)

**Comment by barry-far** [comment]
> All_Configs_Sub.txt -- V2rayN I updated the nodes in V2ray, but none of them changed. It's been a long time. When I clicked the one-key speed test, the core crashed and couldn't run. It didn't happen before. I checked and found that some nodes were incompatible. I saw that the GitHub files were updated all the time. I don't know what's going on. ![image](https://private-user-images.githubusercontent.com/42275612/372700280-5eff14bd-7e1b-475d-9e62-9475913cc356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzU4OTksIm5iZiI6MTcyNzg3NTU5OSwicGF0aCI6Ii80MjI3NTYxMi8zNzI3MDAyODAtNWVmZjE0YmQtN2UxYi00NzVkLTllNjItOTQ3NTkxM2NjMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEzMjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTEzMTkwNTk3OTk3YzMxMGUxZGY2ODA0YTUxZmJlYjhmYTkyZDQwZDFkYjM5MTdiNzZkMDVmODk3ZmE4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JwCDRCtNG9de3lmj-xoCmn-ZsBKsHLbNPrG3DzNe2d0)

Hi @YJL12345 

thanks for your support❤️

Please use hiddify app instead to be not crashed anymore , or you can user splitted sublinks e.x. https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt
