### ISSUE TITLE
patch warp error

### ISSUE THREAD

**Issue by profesy** [barry-far/V2ray-Configs#73]
good afternoon, when adding the configuration Warp_sub.txt it gives an error
patch warp error
![2024-10-07 234957](https://github.com/user-attachments/assets/9f8975cc-ea8d-43ab-867b-bf11b08e35f1)

thanks

**Comment by profesy** [comment]
![2024-10-08 150238](https://github.com/user-attachments/assets/3e09ab8e-479a-4b45-962a-e72059bf147a)
the error is repeated with a different number

**Comment by profesy** [comment]
![2024-10-09 131003](https://github.com/user-attachments/assets/996b2c32-dd1a-4bb8-9af7-0f2df7dcb8cf)
constant error, only the number is different

thanks

**Comment by barry-far** [comment]
Hey @profesy ,
It is because you are using the internet blocking Cloudflare & warp ips.
Try first to connect to a VPN then try again.
