### ISSUE TITLE
patch warp error

### ISSUE THREAD

**Issue by profesy** [barry-far/V2ray-Configs#74]
[patch warp error](https://github.com/barry-far/V2ray-Configs/issues/73)
https://raw.githubusercontent.com/barry-far/V2ray-Configs/refs/heads/main/Warp_sub.txt    VPN connection gives an error despite your advice

![2024-10-14 005011](https://github.com/user-attachments/assets/21221387-fcb7-42ca-a6ed-bea69625ab17)
please tell me what needs to be done, thanks in advance

**Comment by profesy** [comment]
![2024-10-14 204249](https://github.com/user-attachments/assets/6a5a0d2a-3cdd-4592-8a23-8efb53ac4384)
![2024-10-14 204443](https://github.com/user-attachments/assets/dc6d4f62-1de5-4ed1-a782-7dc6ddc60b53)
![2024-10-14 204747](https://github.com/user-attachments/assets/23352633-ca66-4d38-ab62-ed4f75fbd488)
VPN connection, 
1.4, 1.5.2, 2.5.7  Hiddify

**Comment by profesy** [comment]
![2024-10-16 194449](https://github.com/user-attachments/assets/6dd2343e-f5be-4d10-a534-f5ee7eb8456e)
incorrect configuration

**Comment by barry-far** [comment]
Hey @profesy ,
It is because you are using the internet blocking Cloudflare & warp ips.
Try first to connect to a VPN then try again.
