### ISSUE TITLE
How do I use it with sni/bug host?

### ISSUE THREAD

**Issue by DogancanYr** [barry-far/V2ray-Configs#78]
I am a newbie in these things, can you help or is there a telegram group that can help.

**Comment by barry-far** [comment]
Hey @DogancanYr 
you only need to read this instructions :
https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app

**Comment by DogancanYr** [comment]
> Hey @DogancanYr you only need to read this instructions : https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app

Okay but can't I make settings on the servers, or don't some servers come in different configurations?

**Comment by barry-far** [comment]
> > Hey @DogancanYr you only need to read this instructions : https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app
> 
> Okay but can't I make settings on the servers, or don't some servers come in different configurations?

Hey @DogancanYr ,
Absolutely you can change configs on Hiddify. Make sure you are using latest version & you will be fine :)

**Comment by DogancanYr** [comment]
> > > Hey @DogancanYr you only need to read this instructions : https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app
> > 
> > 
> > Okay but can't I make settings on the servers, or don't some servers come in different configurations?
> 
> Hey @DogancanYr , Absolutely you can change configs on Hiddify. Make sure you are using latest version & you will be fine :)

Okay but how can I change it and what values can I use. There is no guide.

**Comment by barry-far** [comment]
> > > > Hey @DogancanYr you only need to read this instructions : https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app
> > > 
> > > 
> > > Okay but can't I make settings on the servers, or don't some servers come in different configurations?
> > 
> > 
> > Hey @DogancanYr , Absolutely you can change configs on Hiddify. Make sure you are using latest version & you will be fine :)
> 
> Okay but how can I change it and what values can I use. There is no guide.

Select the proxies tab the you can change configs manually.
