### ISSUE TITLE
Salut Este un roman care ma poate ajuta cu configuratia corecta pt telekom ? 

### ISSUE THREAD

**Issue by Guntamilutz** [barry-far/V2ray-Configs#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by barry-far** [comment]
Hey you can use this help :
https://github.com/hiddify/Hiddify-Manager/wiki/Tutorial-for-HiddifyNext-app#adding-a-profile-to-the-app
