### ISSUE TITLE
error: v2rayn failed to start the kernel - look at the logs

### ISSUE THREAD

**Issue by T-8000N71** [barry-far/V2ray-Configs#80]
Every time I try to test all servers for speed and latency (ctrl+E), I get an error: "failed to run Core, please see the log".

I checked the log and copied the report to chat gt4 - it says there are no problems. I tried updating the v2rayn client. I tried to install the latest version - it does not help and does not solve this problem in any way.

 I used the config: "[All_Configs_Sub.txt](https://github.com/barry-far/V2ray-Configs/blob/main/All_Configs_Sub.txt)"
 
 I describe step by step the process in which the error comes out, I'm new to github and I don't know how to use it, I use a translator:
 
 in the new version of the program v2rayn 6.60 (yes, in principle, in any version of the program, I tried it on 7.0.6 - the situation is similar)

1. I run v2rayn as an administrator (although this is not important in principle and does not affect in any way, the error still appears early)
2. press ctrl+e (to test the speed and latency of all servers)
3. returns the error "failed to run Core, please see the log"

as a result, I cannot use this list. I have to take any other list since this one doesn't work.

**I'm not sure, but maybe it's because of the number of servers, since there are 4477 of them here
**I tried it on win 10 pro, win 11 pro - the result is the same.
**the rest of the lists are working fine, there may be some kind of error in the list
**the latest versions of the sdk (6-8) from Microsoft are also installed
**I am attaching screenshots with step-by-step actions

<img width="943" alt="additionally1" src="https://github.com/user-attachments/assets/e3198b4d-6387-4012-b80f-da9462098aae">
<img width="1260" alt="step 1" src="https://github.com/user-attachments/assets/edcc4fe2-8455-4c82-b06b-efe3db19bea1">
<img width="660" alt="step 2" src="https://github.com/user-attachments/assets/e7598d8f-fbf5-4674-a3a1-66d061d9b4a3">
<img width="662" alt="step 3" src="https://github.com/user-attachments/assets/708336ca-f618-4635-87fc-22ddff0ea1f4">
<img width="661" alt="step 4" src="https://github.com/user-attachments/assets/a9cd5719-0ec0-40af-b390-09fbb205c19f">

**Comment by T-8000N71** [comment]
Additionally, I would like to leave a comment: as a beginner, I am like a monkey with a grenade in my hands. I don't understand how this whole system works. the instructions do not say anything about this. I would like to see a brief diagram that will depict or describe how this program works in general. the program is overloaded with a bunch of unnecessary functions that are located and named unintuitively. there is no help and hints above the windows and buttons. beginners won't understand how it works. I want to understand how it works.

since I don't know how to use github, I couldn't even describe this error - because I didn't know where to click on this site. chat gpt helped me. since I don't speak English at all. this information should be added to the header of your configs. then it will be much easier to submit a request about errors that occur

**Comment by T-8000N71** [comment]
starting today, it's exactly the same problem with different lists. you have some errors in the configuration files.

you give a comment - will it be fixed or not. I need to understand if I should wait for feedback or if it's easier for me to find other configs, since I'm being ignored.

**Comment by T-8000N71** [comment]
all server lists stopped working "kernel error" failed to start the kernel. v2rayn is no longer working.

**Comment by barry-far** [comment]
Hey @T-8000N71,
Thanks for creating such a perfect issue & telling me the problem you encountered.

Unfortunately, The v2rayn application is unable to handle such an amount of configs. So I suggest you try the hiddify application. Here is the link below:

https://github.com/hiddify/hiddify-next/releases

You can use my subs on there to get connected.

Here is my suggestion to follow too:
https://github.com/barry-far/V2ray-Configs#requirements-and-how-to-use

**Comment by T-8000N71** [comment]
> Hey @T-8000N71, Thanks for creating such a perfect issue & telling me the problem you encountered.
> 
> Unfortunately, The v2rayn application is unable to handle such an amount of configs. So I suggest you try the hiddify application. Here is the link below:
> 
> https://github.com/hiddify/hiddify-next/releases
> 
> You can use my subs on there to get connected.
> 
> Here is my suggestion to follow too: https://github.com/barry-far/V2ray-Configs#requirements-and-how-to-use

it is sad. now no config is running. but I don't really care, I found another program. She's better at everything, works faster. and I don't use this shame anymore.

**Comment by T-8000N71** [comment]
absolutely all configs stopped working. neither configuration works. therefore, I no longer use the misunderstanding under the name v2rayn

**Comment by barry-far** [comment]
> d. now no config is running. but I don't really care, I f

OK dont use any configs. Its not for me to fell shame 🙂💔

**Comment by barry-far** [comment]
There are some other splitted configs you can find through here:
https://github.com/barry-far/V2ray-Configs#usage

**Comment by T-8000N71** [comment]
you don't have an understanding of what real convenience is. if only you had used Russian services at least once. you would understand what maximum convenience is. when everything can be solved through a smartphone. any problem at all. no need to run around with papers. There is no bureaucracy. everything is digital. I pressed 3 buttons and received an extract. I pressed 2 buttons and went to the hospital. No paperwork. the most convenient usability. you don't have any kind of service - everything is made of shit and sticks. that's absolutely anyone. I am at a loss - how could you make an application and not make a function that displays the speed??What kind of idiot should I be!??it's like making a car and deliberately not making it a steering wheel, seat, engine or wheels. more and more handlers are engaged in the development. Have you ever used it

**Comment by T-8000N71** [comment]
and this happens because our people are tougher. They don't tolerate shit. if they don't like the service, they don't use it and immediately leave. you have it there abroad, gays, trannies, niggas and other tolerasty. and as a result, then these bastard niggas rob you, kill you, rape you - they don't work, sell drugs and weapons and at the same time have more rights than white people and live for free on welfare. while whites suffer and live in fear. Fucking niggas. Put everyone in a pit and burn them alive. rather, the nuclear bomb would be thrown off, maybe then the understanding would come that it's time to do business, and not piss in the sand. It's time to make humanoid robots. It's time to build a world. build rockets. to fly to conquer space, and not to support the faggots who made all the movies, TV series, games shit.

and these Arabs are Muslim terrorists. every day someone's clitoris is cut off. then the heads are cut. Terrorists are fuckin'. they would go to live in their fucking mountains and not get involved with people in a civilized society. Bearded bastards didn't give a fuck to the world. no companies have been built. not one invention has been made all the time. They'll just burst out. They kill. They rape me. they cut and fuck sheep. fuck off to the mountains and fuck with your sheep there. without the Internet. without computers. without smartphones. without electricity.
