### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Darkcode-it** [barry-far/V2ray-Configs#83]
ایشون (yebekhe)چرا اکانتشو پاک کردن کە شما در لیست همکارا گزاشتە بودین

**Comment by barry-far** [comment]
سلام @Darkcode-it 
بله ایشون طبق این توییت اعلام کردن که دیگه فعالیت ندارن و نیستن:
https://x.com/yebekhe/status/1849760040527237135

اما به خاطر کمکشون و زحماتشون از روز اول اسمشون در Readme پروژه بود.

**Comment by Darkcode-it** [comment]
سلام استاد بلە ممنون زندە باشین اگە اجازە بدین من در فصل زمستون رو پروژتون
کار کنم.

**Comment by Darkcode-it** [comment]
من الانم سەتا کانفیگ دارم کار میکنن از این اقای ybekhe
