### ISSUE TITLE
V2rayng

### ISSUE THREAD

**Issue by earthen3** [barry-far/V2ray-Configs#85]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by b8t6vi8terrrrrrrrrrrrrrrrrrrrrrrrr** [comment]
https://github.com/b8t6vi8terrrrrrrrrrrrrrrrrrrrrrrrr/Pronouns/commit/9f518415eefeb1e98dc1078c3c039998ed9b9883#commitcomment-149300328
